/*
 * VariableEditorPanel.java
 *
 * Created on 29 July 2008, 15:29
 */
package canreg.client.gui.components;

import canreg.client.gui.dataentry.RecordEditorPanel;
import canreg.client.gui.tools.MaxLengthDocument;
import canreg.common.DatabaseVariablesListElement;
import canreg.server.database.Dictionary;
import canreg.server.database.DictionaryEntry;
import java.awt.Component;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;

/**
 *
 * @author  ervikm
 */
public class VariableEditorPanel extends javax.swing.JPanel implements ActionListener {

    /**
     * 
     */
    protected DatabaseVariablesListElement databaseListElement;
    /**
     * 
     */
    protected Map<String, DictionaryEntry> possibleValuesMap = null;
    /**
     * 
     */
    protected int maxLength;
    /**
     * 
     */
    protected java.awt.Color mandatoryMissingColor = java.awt.Color.PINK;
    private Dictionary dictionary;

    /** Creates new form VariableEditorPanel */
    public VariableEditorPanel() {
        initComponents();
        
        codeTextField.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                componentFocusGained(evt);
            }
        });
    }

    /**
     * 
     * @return
     */
    public String getKey() {
        return databaseListElement.getDatabaseVariableName();
    }

    /**
     * 
     * @param aThis
     */
    public void setPropertyChangeListener(RecordEditorPanel aThis) {
        codeTextField.addPropertyChangeListener(aThis);
    }

    /**
     * 
     * @param listener
     */
    public void setDocumentListener(DocumentListener listener) {
        codeTextField.getDocument().addDocumentListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variableNameLabel = new javax.swing.JLabel();
        splitPane1 = new javax.swing.JSplitPane();
        splitPane2 = new javax.swing.JSplitPane();
        categoryTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        codeTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(VariableEditorPanel.class);
        variableNameLabel.setText(resourceMap.getString("variableNameLabel.text")); // NOI18N
        variableNameLabel.setName("variableNameLabel"); // NOI18N

        splitPane1.setResizeWeight(0.5);
        splitPane1.setFocusable(false);
        splitPane1.setName("splitPane1"); // NOI18N

        splitPane2.setResizeWeight(0.5);
        splitPane2.setFocusable(false);
        splitPane2.setName("splitPane2"); // NOI18N

        categoryTextField.setEditable(false);
        categoryTextField.setText(resourceMap.getString("categoryTextField.text")); // NOI18N
        categoryTextField.setFocusable(false);
        categoryTextField.setName("categoryTextField"); // NOI18N
        categoryTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickHandler(evt);
            }
        });
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });
        splitPane2.setLeftComponent(categoryTextField);

        descriptionTextField.setEditable(false);
        descriptionTextField.setText(resourceMap.getString("descriptionTextField.text")); // NOI18N
        descriptionTextField.setFocusable(false);
        descriptionTextField.setName("descriptionTextField"); // NOI18N
        descriptionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionTextFieldMouseClicked(evt);
            }
        });
        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });
        splitPane2.setRightComponent(descriptionTextField);

        splitPane1.setRightComponent(splitPane2);

        codeTextField.setText(resourceMap.getString("codeTextField.text")); // NOI18N
        codeTextField.setName("codeTextField"); // NOI18N
        codeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codeTextFieldActionPerformed(evt);
            }
        });
        splitPane1.setLeftComponent(codeTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(variableNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(splitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(variableNameLabel)
                    .addComponent(splitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void mouseClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickHandler

    if (databaseListElement.getVariableType().equalsIgnoreCase("dict")) {
        // System.out.println("Coucou");
        if (possibleValuesMap == null) {
            JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Empty_dictionary."), java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Warning"), JOptionPane.WARNING_MESSAGE);
        } else {
            DictionaryEntry[] possibleValuesArray = new DictionaryEntry[possibleValuesMap.size()];
            Iterator<String> it = possibleValuesMap.keySet().iterator();
            int i = 0;
            while (it.hasNext()) {
                possibleValuesArray[i++] = possibleValuesMap.get(it.next());
            }
            DictionaryEntry selectedValue = (DictionaryEntry) JOptionPane.showInternalInputDialog(this,
                    java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Choose_one"), java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Input"),
                    JOptionPane.INFORMATION_MESSAGE, null,
                    possibleValuesArray, possibleValuesArray[0]);
            if (selectedValue != null) {
                setValue(selectedValue.getCode());
                descriptionTextField.setText(selectedValue.getDescription());
            }
        }
    } else {
        // Do nothing
        // This should never happen...
    }
}//GEN-LAST:event_mouseClickHandler

private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_categoryTextFieldActionPerformed

private void codeTextFieldActionPerformed(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codeTextFieldActionPerformed
    try {
        lookUpAndSetDescription();
    } catch (NullPointerException e) {
        JOptionPane.showInternalMessageDialog(this, codeTextField.getText() + " " 
                + java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("_is_not_a_valid_dictionary_code."), java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Error"), JOptionPane.ERROR_MESSAGE);
    }
    updateFilledInStatusColor();
}//GEN-LAST:event_codeTextFieldActionPerformed

private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_descriptionTextFieldActionPerformed

private void descriptionTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTextFieldMouseClicked
    mouseClickHandler(evt);
}//GEN-LAST:event_descriptionTextFieldMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField categoryTextField;
    protected javax.swing.JTextField codeTextField;
    protected javax.swing.JTextField descriptionTextField;
    protected javax.swing.JSplitPane splitPane1;
    protected javax.swing.JSplitPane splitPane2;
    private javax.swing.JLabel variableNameLabel;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     * @param variableName
     */
    protected void setVariableName(String variableName) {
        variableNameLabel.setText(variableName);
    }

    /**
     * 
     * @param value
     */
    public void setValue(String value) {
        codeTextField.setText(value);
        try {
            lookUpAndSetDescription();
        } catch (NullPointerException e) {
            descriptionTextField.setText(java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Dictionary_Error"));
        }
        updateFilledInStatusColor();
    }

    private void lookUpAndSetDescription() throws NullPointerException {
        if (codeTextField.getText().trim().length() > 0) {
            if (possibleValuesMap != null) {
                try {
                    if (dictionary.isCompoundDictionary()) {
                        categoryTextField.setText(possibleValuesMap.get(
                                codeTextField.getText().substring(0, dictionary.getCodeLength())).getDescription());
                    }
                    descriptionTextField.setText(possibleValuesMap.get(codeTextField.getText()).getDescription());
                } catch (NullPointerException e) {
                    throw e;
                }
            }
        } else {
            categoryTextField.setText("");
            descriptionTextField.setText("");
        }
    }

    private void updateFilledInStatusColor() {
        if (databaseListElement.getFillInStatus().equalsIgnoreCase("Mandatory")) {
            if (codeTextField.getText().trim().length() == 0) {
                codeTextField.setBackground(mandatoryMissingColor);
            } else {
                codeTextField.setBackground(java.awt.SystemColor.text);
            }
        }
    }

    /**
     * 
     * @return
     */
    public Object getValue() {
        Object valueObject = null;
        String valueString = codeTextField.getText();
        if (databaseListElement.getVariableType().equalsIgnoreCase("Number") ||
                databaseListElement.getVariableType().equalsIgnoreCase("Date")) {
            if (valueString.trim().length() > 0) {
                try {
                    valueObject = Integer.parseInt(valueString.trim());
                } catch (NumberFormatException numberFormatException) {
                    valueObject = -1;
                    System.out.println(databaseListElement.getShortName() + "" + valueString);
                }
            } else {
                valueObject = null;
            }
        } else {
            valueObject = valueString;
        }
        return valueObject;
    }

    /**
     * 
     * @param databaseListElement
     */
    public void setDatabaseVariablesListElement(DatabaseVariablesListElement databaseListElement) {
        this.databaseListElement = databaseListElement;
        setVariableName(databaseListElement.getFullName());
        if (databaseListElement.getDictionaryID() < 0) {
            splitPane1.remove(1);
        }
        String fillInStatus = databaseListElement.getFillInStatus();
        if (fillInStatus.equalsIgnoreCase("Automatic")) {
            codeTextField.setFocusable(false);
            codeTextField.setEditable(false);
        } else if (fillInStatus.equalsIgnoreCase("Mandatory")) {
            codeTextField.setBackground(mandatoryMissingColor);
        }

        // String variableType = databaseListElement.getVariableType();
        descriptionTextField.setVisible(false);
        categoryTextField.setVisible(false);
        setMaximumLength(databaseListElement.getVariableLength());
    }

    /**
     * 
     * @param dictionary
     */
    public void setDictionary(Dictionary dictionary) {
        this.dictionary = dictionary;
        if (dictionary != null) {
            if (dictionary.isCompoundDictionary()) {
                categoryTextField.setVisible(true);
            }
            descriptionTextField.setVisible(true);
            setPossibleValues(dictionary.getDictionaryEntries());
        }
    }

    private void setPossibleValues(Map<String, DictionaryEntry> possibleValues) {
        this.possibleValuesMap = possibleValues;
        DictionaryEntry m;
        if (possibleValuesMap == null) {
            splitPane2.setVisible(false);
        } else {
            m = possibleValuesMap.get(getValue());
            if (m != null) {
                descriptionTextField.setText(m.getDescription());
            }
        }
    }

    /**
     * 
     * @param length
     */
    protected void setMaximumLength(int length) {
        this.maxLength = length;
        if (this.maxLength > 0) {
            codeTextField.setDocument(new MaxLengthDocument(maxLength, this));
        }
    }

    /**
     * 
     * @param evt
     */
    protected void componentFocusGained(java.awt.event.FocusEvent evt) {
        Component focusedComponent = evt.getComponent();
        Point point = focusedComponent.getLocation();
        point.y += 42; // Trial and error
        this.scrollRectToVisible(new Rectangle(point));
    }

    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equalsIgnoreCase("Max length reached")) {
            try{
            lookUpAndSetDescription();
            } catch (NullPointerException ne){
                descriptionTextField.setText(java.util.ResourceBundle.getBundle("canreg/client/gui/components/resources/VariableEditorPanel").getString("Dictionary_Error"));
            }
            updateFilledInStatusColor();
        }
    }
}
