/*
 * DatabaseVariableEditorInternalFrame.java
 *
 * Created on 21-Jan-2010, 11:18:02
 */
package canreg.client.gui.management;

import canreg.common.DatabaseDictionaryListElement;
import canreg.common.DatabaseGroupsListElement;
import canreg.common.DatabaseVariablesListElement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author ervikm
 */
public class DatabaseVariableEditorInternalFrame extends javax.swing.JInternalFrame {

    private ActionListener listener;
    public final static String UPDATED = "varaiable_updated";

    /** Creates new form DatabaseVariableEditorInternalFrame */
    public DatabaseVariableEditorInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseVariableEditor = new canreg.client.gui.management.DatabaseVariableEditor();

        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(DatabaseVariableEditorInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(DatabaseVariableEditorInternalFrame.class, this);
        okButton.setAction(actionMap.get("okAction")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancelAction")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        databaseVariableEditor.setName("databaseVariableEditor"); // NOI18N
        jScrollPane1.setViewportView(databaseVariableEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancelAction() {
        this.dispose();
    }

    @Action
    public void okAction() {
        try {
            databaseVariableEditor.refreshDatabaseVariablesListElement();
            listener.actionPerformed(new ActionEvent(this, 0, UPDATED));
            this.dispose();
        } catch (DatabaseVariablesListException ex) {
            JOptionPane.showInternalMessageDialog(rootPane, ex.getDatabaseVariablesListElement().getDatabaseVariableName() + " : " + ex.getError());
            Logger.getLogger(DatabaseVariableEditorInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setDatabaseVariablesListElement(DatabaseVariablesListElement databaseVariablesListElement) {
        // this.setTitle(databaseVariablesListElement.getDatabaseVariableName());
        databaseVariableEditor.setDatabaseVariablesListElement(databaseVariablesListElement);
    }

    public void setGroups(DatabaseGroupsListElement[] groups) {
        databaseVariableEditor.setGroups(groups);
    }

    public void setDictionaries(DatabaseDictionaryListElement[] dictionaries) {
        databaseVariableEditor.setDictionaries(dictionaries);
    }

    public void setActionListener(ActionListener listener) {
        this.listener = listener;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private canreg.client.gui.management.DatabaseVariableEditor databaseVariableEditor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
