/*
 * EditDatabaseVariableJPanel.java
 *
 * Created on 06-Jan-2009, 16:15:30
 */

package canreg.client.gui.management;

import canreg.common.DatabaseVariablesListElement;

/**
 *
 * @author ervikm
 */
public class EditDatabaseVariableJPanel extends javax.swing.JPanel {
    private DatabaseVariablesListElement dble;

    /** Creates new form EditDatabaseVariableJPanel */
    public EditDatabaseVariableJPanel() {
        initComponents();
    }
    /**
     * @param dble the dble to set
     */
    void setDble(DatabaseVariablesListElement dble) {
        this.dble=dble;
        variableNameLabel.setText(dble.getFullName());
        jComboBox1.setSelectedItem(dble.getTable());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        variableNameLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Patient", "Tumour", "Source" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(EditDatabaseVariableJPanel.class);
        variableNameLabel.setText(resourceMap.getString("variableNameLabel.text")); // NOI18N
        variableNameLabel.setName("variableNameLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(variableNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(variableNameLabel)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel variableNameLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dble
     */
    public DatabaseVariablesListElement getDble() {
        //update dble
        dble.setDatabaseTableName(jComboBox1.getSelectedItem().toString());
        return dble;
    }
}
