/**
 * CanReg5 - a tool to input, store, check and analyse cancer registry data.
 * Copyright (C) 2008-2015  International Agency for Research on Cancer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Morten Johannes Ervik, CSU/IARC, ervikm@iarc.fr
 */

/*
 * EditDatabaseVariableTableAssociationInternalFrame.java
 *
 * Created on 06-Jan-2009, 16:19:01
 */
package canreg.client.gui.management;

import canreg.common.DatabaseIndexesListElement;
import canreg.common.DatabaseVariablesListElement;
import canreg.common.Globals;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JDesktopPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.jdesktop.application.Action;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author ervikm
 */
public class EditDatabaseVariableTableAssociationInternalFrame extends javax.swing.JInternalFrame {

    private Document doc;
    private JDesktopPane dtp;
    private TreeMap<String, EditDatabaseVariableTableAssociationJPanel> map;
    private String fileName;

    /** Creates new form EditDatabaseVariableTableAssociationInternalFrame */
    public EditDatabaseVariableTableAssociationInternalFrame() {
        initComponents();
        variablesScrollPane.getVerticalScrollBar().setUnitIncrement(16);
    }

    public void setDesktopPane(JDesktopPane dtp) {
        this.dtp = dtp;
    }

    public boolean loadSystemDefinition(String fileName) throws FileNotFoundException, SAXException, IOException, ParserConfigurationException {
        this.fileName = fileName;
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        DocumentBuilder db = dbf.newDocumentBuilder();
        doc = db.parse(new File(fileName));
        boolean success = false;
        variablesAndTableEditorsPanel.removeAll();
        map = new TreeMap<String, EditDatabaseVariableTableAssociationJPanel>();
        DatabaseVariablesListElement[] dbles = canreg.common.Tools.getVariableListElements(doc, Globals.NAMESPACE);
        for (DatabaseVariablesListElement dble : dbles) {
            if (dble.getGroupID() > 0) {
                EditDatabaseVariableTableAssociationJPanel edvjp = new EditDatabaseVariableTableAssociationJPanel();
                edvjp.setDble(dble);
                map.put(dble.getShortName(), edvjp);
                variablesAndTableEditorsPanel.add(edvjp);
                edvjp.setVisible(true);
            }
        }
        variablesAndTableEditorsPanel.revalidate();
        variablesAndTableEditorsPanel.repaint();
        return success;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        variablesAndTablesPanel = new javax.swing.JPanel();
        variablesLabel = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        variablesScrollPane = new javax.swing.JScrollPane();
        variablesAndTableEditorsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(EditDatabaseVariableTableAssociationInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(EditDatabaseVariableTableAssociationInternalFrame.class, this);
        saveButton.setAction(actionMap.get("saveAction")); // NOI18N
        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setName("saveButton"); // NOI18N

        variablesAndTablesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        variablesAndTablesPanel.setName("variablesAndTablesPanel"); // NOI18N

        variablesLabel.setText(resourceMap.getString("variablesLabel.text")); // NOI18N
        variablesLabel.setName("variablesLabel"); // NOI18N

        tableLabel.setText(resourceMap.getString("tableLabel.text")); // NOI18N
        tableLabel.setName("tableLabel"); // NOI18N

        variablesScrollPane.setName("variablesScrollPane"); // NOI18N

        variablesAndTableEditorsPanel.setName("variablesAndTableEditorsPanel"); // NOI18N
        variablesAndTableEditorsPanel.setLayout(new java.awt.GridLayout(0, 1));
        variablesScrollPane.setViewportView(variablesAndTableEditorsPanel);

        javax.swing.GroupLayout variablesAndTablesPanelLayout = new javax.swing.GroupLayout(variablesAndTablesPanel);
        variablesAndTablesPanel.setLayout(variablesAndTablesPanelLayout);
        variablesAndTablesPanelLayout.setHorizontalGroup(
            variablesAndTablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variablesAndTablesPanelLayout.createSequentialGroup()
                .addComponent(variablesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(217, 217, 217)
                .addComponent(tableLabel))
            .addComponent(variablesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        variablesAndTablesPanelLayout.setVerticalGroup(
            variablesAndTablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variablesAndTablesPanelLayout.createSequentialGroup()
                .addGroup(variablesAndTablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variablesLabel)
                    .addComponent(tableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variablesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(variablesAndTablesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variablesAndTablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void saveAction() {
        //for each variable of the doc update the Table information...
        TreeMap<String, String> variablesToTableMap = new TreeMap<String, String>();

        NodeList nl = doc.getElementsByTagName(Globals.NAMESPACE + "variable");

        for (int i = 0; i < nl.getLength(); i++) {
            Element e = (Element) nl.item(i);
            String shortName = e.getElementsByTagName(Globals.NAMESPACE + "short_name").item(0).getTextContent();
            String tableName = e.getElementsByTagName(Globals.NAMESPACE + "table").item(0).getTextContent();
            Element oldChildElement = null;
            oldChildElement = (Element) e.getElementsByTagName(Globals.NAMESPACE + "table").item(0);
            Element newChildElement = doc.createElement(Globals.NAMESPACE + "table");
            EditDatabaseVariableTableAssociationJPanel panel = map.get(shortName);
            if (panel != null) {
                newChildElement.appendChild(doc.createTextNode(panel.getDble().getDatabaseTableName()));
                e.replaceChild(newChildElement, oldChildElement);
                tableName = panel.getDble().getDatabaseTableName();
            }
            variablesToTableMap.put(canreg.common.Tools.toUpperCaseStandardized(shortName), tableName);
        }

        // Update the Indexes part
        //
        Map<String, DatabaseIndexesListElement> indexMap = canreg.common.Tools.buildIndexMap(Globals.PATIENT_TABLE_NAME, doc, Globals.NAMESPACE, null);
        indexMap.putAll(canreg.common.Tools.buildIndexMap(Globals.TUMOUR_TABLE_NAME, doc, Globals.NAMESPACE, null));

        Element parentElement = doc.createElement(Globals.NAMESPACE + "indexes");

        // Split the indexes that needs to be split
        indexMap = canreg.server.management.SystemDefinitionConverter.splitIndexMapInTumourAndPatient(indexMap, variablesToTableMap);

        Element element;
        // then build doc for the indexes
        Set<String> indexNames = indexMap.keySet();
        for (String indexName : indexNames) {
            String table = null;

            element = doc.createElement(Globals.NAMESPACE + "index");
            parentElement.appendChild(element);
            Element childElement = createElement(Globals.NAMESPACE + "name", indexName);
            element.appendChild(childElement);

            LinkedList<String> variablesInThisIndex = indexMap.get(indexName).getVariableNamesInIndex();

            String tableOfThisIndex = variablesToTableMap.get(
                    canreg.common.Tools.toUpperCaseStandardized(variablesInThisIndex.getFirst()));
            childElement = createElement(Globals.NAMESPACE + "table", tableOfThisIndex);
            element.appendChild(childElement);
            for (String variableName : variablesInThisIndex) {
                Element thisElement = doc.createElement(Globals.NAMESPACE + "indexed_variable");
                element.appendChild(thisElement);
                thisElement.appendChild(createElement(Globals.NAMESPACE + "variable_name", variableName));
            }
        }
        // switch the old with the new indexes part
        Element root = doc.getDocumentElement();
        Element oldIndexesElement = (Element) doc.getElementsByTagName(Globals.NAMESPACE + "indexes").item(0);
        root.replaceChild(parentElement, oldIndexesElement);

        // write the xml file
        canreg.server.xml.Tools.writeXmlFile(doc, fileName);
        this.dispose();
    }

    private Element createElement(String variableName, String value) {
        Element childElement = doc.createElement(variableName);
        childElement.appendChild(doc.createTextNode(value));
        return childElement;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JButton saveButton;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JPanel variablesAndTableEditorsPanel;
    private javax.swing.JPanel variablesAndTablesPanel;
    private javax.swing.JLabel variablesLabel;
    private javax.swing.JScrollPane variablesScrollPane;
    // End of variables declaration//GEN-END:variables
}
