/**
 * CanReg5 - a tool to input, store, check and analyse cancer registry data.
 * Copyright (C) 2008-2015  International Agency for Research on Cancer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Morten Johannes Ervik, CSU/IARC, ervikm@iarc.fr
 */

/*
 * UserManagerInternalFrame.java
 *
 * Created on 05-May-2009, 16:55:02
 */
package canreg.client.gui.management;

import canreg.client.CanRegClientApp;
import canreg.common.Globals;
import canreg.common.PasswordService;
import canreg.exceptions.SystemUnavailableException;
import canreg.server.database.RecordLockedException;
import canreg.common.database.User;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author ervikm
 */
public class UserManagerInternalFrame extends javax.swing.JInternalFrame {

    private List<User> users;
    private DefaultListModel usersListModel;

    /** Creates new form UserManagerInternalFrame */
    public UserManagerInternalFrame() {
        initComponents();
        tabbedPane.remove(lockedRecordsPanel);
        initData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        currentUserPanel = new javax.swing.JPanel();
        passwordPanel = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        confirmNewPasswordLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        confirmNewPasswordField = new javax.swing.JPasswordField();
        changePasswordButton = new javax.swing.JButton();
        lockedRecordsPanel = new javax.swing.JPanel();
        lockedRecordsScrollPane = new javax.swing.JScrollPane();
        lockedRecordsList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        databasePasswordPanel = new javax.swing.JPanel();
        passwordPanel1 = new javax.swing.JPanel();
        newDBPasswordLabel = new javax.swing.JLabel();
        confirmNewDBPasswordLabel = new javax.swing.JLabel();
        newDBPasswordField = new javax.swing.JPasswordField();
        confirmNewDBPasswordField = new javax.swing.JPasswordField();
        changeDBPasswordButton = new javax.swing.JButton();
        currentDBPasswordLabel = new javax.swing.JLabel();
        currentDBPasswordField = new javax.swing.JPasswordField();
        userManagerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userRightLevelComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList();
        realNameTextField = new javax.swing.JTextField();
        realNameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(UserManagerInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        tabbedPane.setName("tabbedPane"); // NOI18N

        currentUserPanel.setName("currentUserPanel"); // NOI18N

        passwordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("passwordPanel.border.title"))); // NOI18N
        passwordPanel.setName("passwordPanel"); // NOI18N

        newPasswordLabel.setText(resourceMap.getString("newPasswordLabel.text")); // NOI18N
        newPasswordLabel.setName("newPasswordLabel"); // NOI18N

        confirmNewPasswordLabel.setText(resourceMap.getString("confirmNewPasswordLabel.text")); // NOI18N
        confirmNewPasswordLabel.setName("confirmNewPasswordLabel"); // NOI18N

        newPasswordField.setText(resourceMap.getString("newPasswordField.text")); // NOI18N
        newPasswordField.setName("newPasswordField"); // NOI18N

        confirmNewPasswordField.setText(resourceMap.getString("confirmNewPasswordField.text")); // NOI18N
        confirmNewPasswordField.setName("confirmNewPasswordField"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(UserManagerInternalFrame.class, this);
        changePasswordButton.setAction(actionMap.get("changePasswordAction")); // NOI18N
        changePasswordButton.setText(resourceMap.getString("changePasswordButton.text")); // NOI18N
        changePasswordButton.setToolTipText(resourceMap.getString("changePasswordButton.toolTipText")); // NOI18N
        changePasswordButton.setName("changePasswordButton"); // NOI18N

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmNewPasswordLabel)
                            .addComponent(newPasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(confirmNewPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmNewPasswordLabel)
                    .addComponent(confirmNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePasswordButton))
        );

        javax.swing.GroupLayout currentUserPanelLayout = new javax.swing.GroupLayout(currentUserPanel);
        currentUserPanel.setLayout(currentUserPanelLayout);
        currentUserPanelLayout.setHorizontalGroup(
            currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        currentUserPanelLayout.setVerticalGroup(
            currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentUserPanelLayout.createSequentialGroup()
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        tabbedPane.addTab(resourceMap.getString("currentUserPanel.TabConstraints.tabTitle"), currentUserPanel); // NOI18N

        lockedRecordsPanel.setName("lockedRecordsPanel"); // NOI18N

        lockedRecordsScrollPane.setName("lockedRecordsScrollPane"); // NOI18N

        lockedRecordsList.setName("lockedRecordsList"); // NOI18N
        lockedRecordsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lockedRecordsListValueChanged(evt);
            }
        });
        lockedRecordsScrollPane.setViewportView(lockedRecordsList);

        jButton1.setAction(actionMap.get("refreshLockedRecordsAction")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout lockedRecordsPanelLayout = new javax.swing.GroupLayout(lockedRecordsPanel);
        lockedRecordsPanel.setLayout(lockedRecordsPanelLayout);
        lockedRecordsPanelLayout.setHorizontalGroup(
            lockedRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lockedRecordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lockedRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lockedRecordsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        lockedRecordsPanelLayout.setVerticalGroup(
            lockedRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lockedRecordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lockedRecordsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        tabbedPane.addTab(resourceMap.getString("lockedRecordsPanel.TabConstraints.tabTitle"), lockedRecordsPanel); // NOI18N

        databasePasswordPanel.setName("databasePasswordPanel"); // NOI18N

        passwordPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("passwordPanel1.border.title"))); // NOI18N
        passwordPanel1.setName("passwordPanel1"); // NOI18N

        newDBPasswordLabel.setText(resourceMap.getString("newDBPasswordLabel.text")); // NOI18N
        newDBPasswordLabel.setName("newDBPasswordLabel"); // NOI18N

        confirmNewDBPasswordLabel.setText(resourceMap.getString("confirmNewDBPasswordLabel.text")); // NOI18N
        confirmNewDBPasswordLabel.setName("confirmNewDBPasswordLabel"); // NOI18N

        newDBPasswordField.setName("newDBPasswordField"); // NOI18N

        confirmNewDBPasswordField.setName("confirmNewDBPasswordField"); // NOI18N

        changeDBPasswordButton.setAction(actionMap.get("changeDBPasswordAction")); // NOI18N
        changeDBPasswordButton.setText(resourceMap.getString("changeDBPasswordButton.text")); // NOI18N
        changeDBPasswordButton.setToolTipText(resourceMap.getString("changeDBPasswordButton.toolTipText")); // NOI18N
        changeDBPasswordButton.setActionCommand(resourceMap.getString("changeDBPasswordButton.actionCommand")); // NOI18N
        changeDBPasswordButton.setName("changeDBPasswordButton"); // NOI18N

        currentDBPasswordLabel.setText(resourceMap.getString("currentDBPasswordLabel.text")); // NOI18N
        currentDBPasswordLabel.setName("currentDBPasswordLabel"); // NOI18N

        currentDBPasswordField.setName("currentDBPasswordField"); // NOI18N

        javax.swing.GroupLayout passwordPanel1Layout = new javax.swing.GroupLayout(passwordPanel1);
        passwordPanel1.setLayout(passwordPanel1Layout);
        passwordPanel1Layout.setHorizontalGroup(
            passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwordPanel1Layout.createSequentialGroup()
                            .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(currentDBPasswordLabel)
                                .addComponent(newDBPasswordLabel))
                            .addGap(27, 27, 27)
                            .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newDBPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addComponent(currentDBPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                            .addContainerGap())
                        .addGroup(passwordPanel1Layout.createSequentialGroup()
                            .addComponent(confirmNewDBPasswordLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(confirmNewDBPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanel1Layout.createSequentialGroup()
                        .addComponent(changeDBPasswordButton)
                        .addContainerGap())))
        );
        passwordPanel1Layout.setVerticalGroup(
            passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanel1Layout.createSequentialGroup()
                .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentDBPasswordLabel)
                    .addComponent(currentDBPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDBPasswordLabel)
                    .addComponent(newDBPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmNewDBPasswordLabel)
                    .addComponent(confirmNewDBPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeDBPasswordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout databasePasswordPanelLayout = new javax.swing.GroupLayout(databasePasswordPanel);
        databasePasswordPanel.setLayout(databasePasswordPanelLayout);
        databasePasswordPanelLayout.setHorizontalGroup(
            databasePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        databasePasswordPanelLayout.setVerticalGroup(
            databasePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePasswordPanelLayout.createSequentialGroup()
                .addComponent(passwordPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tabbedPane.addTab(resourceMap.getString("databasePasswordPanel.TabConstraints.tabTitle"), databasePasswordPanel); // NOI18N

        userManagerPanel.setName("userManagerPanel"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        usernameTextField.setEditable(false);
        usernameTextField.setText(resourceMap.getString("usernameTextField.text")); // NOI18N
        usernameTextField.setName("usernameTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        userRightLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userRightLevelComboBox.setName("userRightLevelComboBox"); // NOI18N

        jButton2.setAction(actionMap.get("resetPasswordAction")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("updateUserAction")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton4.setAction(actionMap.get("deleteUserAction")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jButton5.setAction(actionMap.get("addUserAction")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        usersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        usersList.setName("usersList"); // NOI18N
        usersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                usersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(usersList);

        realNameTextField.setText(resourceMap.getString("realNameTextField.text")); // NOI18N
        realNameTextField.setName("realNameTextField"); // NOI18N

        realNameLabel.setText(resourceMap.getString("realNameLabel.text")); // NOI18N
        realNameLabel.setName("realNameLabel"); // NOI18N

        emailTextField.setText(resourceMap.getString("emailTextField.text")); // NOI18N
        emailTextField.setName("emailTextField"); // NOI18N

        emailLabel.setText(resourceMap.getString("emailLabel.text")); // NOI18N
        emailLabel.setName("emailLabel"); // NOI18N

        javax.swing.GroupLayout userManagerPanelLayout = new javax.swing.GroupLayout(userManagerPanel);
        userManagerPanel.setLayout(userManagerPanelLayout);
        userManagerPanelLayout.setHorizontalGroup(
            userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userManagerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addGroup(userManagerPanelLayout.createSequentialGroup()
                        .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(realNameLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(userRightLevelComboBox, 0, 331, Short.MAX_VALUE)
                            .addComponent(realNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userManagerPanelLayout.createSequentialGroup()
                        .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        userManagerPanelLayout.setVerticalGroup(
            userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userManagerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userRightLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(11, 11, 11)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        tabbedPane.addTab(resourceMap.getString("userManagerPanel.TabConstraints.tabTitle"), userManagerPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initData() {
        Globals.UserRightLevels level = canreg.client.CanRegClientApp.getApplication().getUserRightLevel();
        if (level == Globals.UserRightLevels.SUPERVISOR) {
            refreshUsersList();
            DefaultComboBoxModel userLevelsModel = new DefaultComboBoxModel(Globals.UserRightLevels.values());
            userRightLevelComboBox.setModel(userLevelsModel);
            usersList.setSelectedIndex(0);
        } else {
            tabbedPane.setEnabledAt(tabbedPane.indexOfComponent(userManagerPanel), false);
            tabbedPane.setEnabledAt(tabbedPane.indexOfComponent(databasePasswordPanel), false);
        }
    }

    private void usersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usersListValueChanged
        User user = (User) usersList.getSelectedValue();
        if (user != null) {
            usernameTextField.setText(user.getUserName());
            userRightLevelComboBox.setSelectedItem(user.getUserRightLevel());
            realNameTextField.setText(user.getRealName());
            emailTextField.setText(user.getEmail());
        } else {
            usernameTextField.setText("");
            userRightLevelComboBox.setSelectedItem(null);
            realNameTextField.setText("");
            emailTextField.setText("");
        }
    }//GEN-LAST:event_usersListValueChanged

    private void lockedRecordsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lockedRecordsListValueChanged
        // TODO add your handling code here:
}//GEN-LAST:event_lockedRecordsListValueChanged

    @Action
    public void addUserAction() {
        User user = new User();
        String userName = JOptionPane.showInputDialog(java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER NAME:"));
        if (userName == null) {
            return;
        }
        while (userName.length() > Globals.MAX_USERNAME_LENGHT) {
            JOptionPane.showInternalMessageDialog(rootPane, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER NAME TOO LONG.") + java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("(MAX ") + Globals.MAX_USERNAME_LENGHT + java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString(" CHARACTERS LONG.)"), java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER NAME TOO LONG."), JOptionPane.ERROR_MESSAGE);
            userName = JOptionPane.showInputDialog(java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER NAME:"));
            if (userName == null) {
                return;
            }
        }
        user.setUserName(userName);
        user.setRealName("");
        user.setEmail("");
        user.setUserRightLevel(Globals.UserRightLevels.ANALYST);
        try {
            String encrypted = PasswordService.getInstance().encrypt(user.getUserName());
            user.setPassword(encrypted.toCharArray());
            canreg.client.CanRegClientApp.getApplication().saveUser(user);
            JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER ADDED. TEMPORARY PASSWORD IS ") + userName + ".");
        } catch (SystemUnavailableException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshUsersList();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeDBPasswordButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JPasswordField confirmNewDBPasswordField;
    private javax.swing.JLabel confirmNewDBPasswordLabel;
    private javax.swing.JPasswordField confirmNewPasswordField;
    private javax.swing.JLabel confirmNewPasswordLabel;
    private javax.swing.JPasswordField currentDBPasswordField;
    private javax.swing.JLabel currentDBPasswordLabel;
    private javax.swing.JPanel currentUserPanel;
    private javax.swing.JPanel databasePasswordPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lockedRecordsList;
    private javax.swing.JPanel lockedRecordsPanel;
    private javax.swing.JScrollPane lockedRecordsScrollPane;
    private javax.swing.JPasswordField newDBPasswordField;
    private javax.swing.JLabel newDBPasswordLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel passwordPanel1;
    private javax.swing.JLabel realNameLabel;
    private javax.swing.JTextField realNameTextField;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel userManagerPanel;
    private javax.swing.JComboBox userRightLevelComboBox;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JList usersList;
    // End of variables declaration//GEN-END:variables

    private void refreshUsersList() {
        try {
            users = canreg.client.CanRegClientApp.getApplication().listUsers();
            usersListModel = new DefaultListModel();
            for (User user : users) {
                usersListModel.addElement(user);
            }
            usersList.setModel(usersListModel);
        } catch (SecurityException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public void changePasswordAction() {
        // are the fields empty?
        if (newPasswordField.getPassword().length == 0 && confirmNewPasswordField.getPassword().length == 0) {
            int answer = JOptionPane.showInternalConfirmDialog(
                    this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("DO YOU REALLY WANT TO SET THE PASSWORD BLANK?"), java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("EMPTY PASSWORD"), JOptionPane.YES_NO_OPTION);
            if (answer != JOptionPane.YES_OPTION) {
                return;
            }
        }

        // verify if passwords match...
        if (Arrays.equals(newPasswordField.getPassword(), confirmNewPasswordField.getPassword())) {
            String passwordString = new String(newPasswordField.getPassword());
            try {
                String encrypted = PasswordService.getInstance().encrypt(passwordString);
                passwordString = null;
                try {
                    canreg.client.CanRegClientApp.getApplication().changePassword(encrypted);
                    JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORD CHANGED."));
                } catch (SecurityException ex) {
                    Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SystemUnavailableException ex) {
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORDS DO NOT MATCH."));
        }
        // set password...
    }

    private void refreshLockedRecordsList() {
    }

    @Action
    public void refreshLockedRecordsAction() {
        refreshLockedRecordsList();
    }

    @Action
    public void updateUserAction() {
        User user = (User) usersList.getSelectedValue();
        boolean okToChange;

        if (user.getUserRightLevel() == Globals.UserRightLevels.SUPERVISOR && (Globals.UserRightLevels) userRightLevelComboBox.getSelectedItem() != Globals.UserRightLevels.SUPERVISOR) {
            okToChange = canRemoveSupervisor(user);
            if (!okToChange) {
                JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("NOT ALLOWED TO CHANGE USER LEVEL OF THE LAST SUPERVISOR USER."));
                return;
            }
        }

//<ictl.co>
        if (CanRegClientApp.getApplication().isLoggedIn() && "admin".equals(user.getUserName())) {
            String currentUserName = CanRegClientApp.getApplication().getLocalSettings().getProperty("username");
            if (!"admin".equals(currentUserName)) {
                JOptionPane.showInternalMessageDialog(this,"Admin user is readonly.");
                throw new SecurityException("Admin user is readonly.");
            }
            if (!CanRegClientApp.getApplication().isCanRegServerRunningOnThisMachine()) {
                JOptionPane.showInternalMessageDialog(this,"Admin user cannot delete from remote connection.");
                throw new SecurityException("Admin user cannot delete from remote connection.");
            }
        }
        //</ictl.co>
        int index = usersList.getSelectedIndex();
        user.setUserRightLevel((Globals.UserRightLevels) userRightLevelComboBox.getSelectedItem());
        user.setEmail(emailTextField.getText());
        user.setRealName(realNameTextField.getText());
        try {
            canreg.client.CanRegClientApp.getApplication().saveUser(user);
            JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("USER UPDATED."));
        } catch (SQLException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshUsersList();
        usersList.setSelectedIndex(index);
    }

    @Action
    public void resetPasswordAction() {
        User user = (User) usersList.getSelectedValue();
        try {
            //<ictl.co>
            if (CanRegClientApp.getApplication().isLoggedIn() && "admin".equals(user.getUserName())) {
                String currentUserName = CanRegClientApp.getApplication().getLocalSettings().getProperty("username");
                if (!"admin".equals(currentUserName)) {
                    JOptionPane.showInternalMessageDialog(this,"Admin user is readonly.");
                    throw new SecurityException("Admin user is readonly.");
                }
                if (!CanRegClientApp.getApplication().isCanRegServerRunningOnThisMachine()) {
                    JOptionPane.showInternalMessageDialog(this,"Admin user cannot delete from remote connection.");
                    throw new SecurityException("Admin user cannot delete from remote connection.");
                }
            }
            //</ictl.co>
            String encrypted = PasswordService.getInstance().encrypt(user.getUserName());
            user.setPassword(encrypted.toCharArray());
            canreg.client.CanRegClientApp.getApplication().saveUser(user);
            JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORD_RESET") + "\n" + java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("TEMPORARY_PASSWORD_IS_") + user.getUserName() + ".");
        } catch (SystemUnavailableException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public void deleteUserAction() {
        User user = (User) usersList.getSelectedValue();
        boolean okToDelete = true;
        if (user.getUserRightLevel() == Globals.UserRightLevels.SUPERVISOR) {
            okToDelete = canRemoveSupervisor(user);
            if (!okToDelete) {
                JOptionPane.showInternalMessageDialog(this, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("CAN_NOT_DELETE_LAST_SUPERVISOR."));
            }
        }
        int id = user.getID();
        if (okToDelete && id > 0) {
            try {
                //<ictl.co>
                if (CanRegClientApp.getApplication().isLoggedIn() && "admin".equals(user.getUserName())) {
                    String currentUserName = CanRegClientApp.getApplication().getLocalSettings().getProperty("username");
                    if (!"admin".equals(currentUserName)) {
                        JOptionPane.showInternalMessageDialog(this,"Admin user is readonly.");
                        throw new SecurityException("Admin user is readonly.");
                    }
                    if (!CanRegClientApp.getApplication().isCanRegServerRunningOnThisMachine()) {
                        JOptionPane.showInternalMessageDialog(this,"Admin user cannot delete from remote connection.");
                        throw new SecurityException("Admin user cannot delete from remote connection.");
                    }
                }
                //</ictl.co>
                canreg.client.CanRegClientApp.getApplication().deleteRecord(id, Globals.USERS_TABLE_NAME);
            } catch (SQLException ex) {
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RecordLockedException ex) {
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SecurityException ex) {
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        refreshUsersList();
    }

    private boolean canRemoveSupervisor(User user) {
        boolean ok = true;
        int numberOfSupervisors = 0;
        for (User tempUser : users) {
            if (tempUser.getUserRightLevel() == Globals.UserRightLevels.SUPERVISOR) {
                numberOfSupervisors++;
            }
        }
        if (numberOfSupervisors == 1) {
            ok = false;
        }
        return ok;
    }

    @Action
    public Task changeDBPasswordAction() {
        changeDBPasswordButton.setEnabled(false);
        if (currentDBPasswordField.getPassword().length == 0) {
            int answer = JOptionPane.showInternalConfirmDialog(
                    databasePasswordPanel, "Are you sure you want to encrypt the database?\n"
                    + "If you loose this password you will loose all the data currently in the database.\n"
                    + "This is a one-way operation, so please make sure to take a backup first.",
                    "Are you sure you want to encrypt the database?", JOptionPane.YES_NO_OPTION);
            if (answer != JOptionPane.YES_OPTION) {
                changeDBPasswordButton.setEnabled(true);
                return null;
            }
        }
        // TODO: Look into removing ecryption of a database...
        // if (newDBPasswordField.getPassword().length == 0) {
        //    int answer = JOptionPane.showInternalConfirmDialog(
        //            databasePasswordPanel, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("DO YOU REALLY WANT TO REMOVE THE PASSWORD?"), java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("EMPTY PASSWORD"), JOptionPane.YES_NO_OPTION);
        //    if (answer != JOptionPane.YES_OPTION) {
        //        return null;
        //    }
        // } else   
        if (newDBPasswordField.getPassword().length < 8) {
            JOptionPane.showInternalMessageDialog(
                    databasePasswordPanel, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("BOOT PASSWORD MUST BE AT LEAST 8 CHARACTERS LONG."), java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORD TOO SHORT"), JOptionPane.YES_NO_OPTION);
            changeDBPasswordButton.setEnabled(true);
            return null;
        }
        // verify if passwords match...
        if (Arrays.equals(
                newDBPasswordField.getPassword(),
                confirmNewDBPasswordField.getPassword())) {
            return new ChangeDBPasswordActionTask(org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class));
        } else {
            JOptionPane.showInternalMessageDialog(databasePasswordPanel, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORDS DO NOT MATCH."));
            changeDBPasswordButton.setEnabled(true);
            return null;
        }
    }

    private class ChangeDBPasswordActionTask extends org.jdesktop.application.Task<Object, Void> {

        private final char[] newPassword;
        private final char[] oldPassword;

        ChangeDBPasswordActionTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to ChangeDBPasswordActionTask fields, here.
            super(app);
            newPassword = newDBPasswordField.getPassword();
            oldPassword = currentDBPasswordField.getPassword();
        }

        @Override
        protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            Boolean success = false;
            try {
                success = canreg.client.CanRegClientApp.getApplication().setDBPassword(newPassword, oldPassword);
            } catch (SecurityException ex) {
                JOptionPane.showInternalMessageDialog(databasePasswordPanel, "Something went wrong during password change.\n" + ex.getLocalizedMessage(), "Password not changed.", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                JOptionPane.showInternalMessageDialog(databasePasswordPanel, "Something went wrong during password change.\n" + ex.getLocalizedMessage(), "Password not changed.", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(UserManagerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return success;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
            Boolean success = (Boolean) result;
            if (success) {
                JOptionPane.showInternalMessageDialog(databasePasswordPanel, java.util.ResourceBundle.getBundle("canreg/client/gui/management/resources/UserManagerInternalFrame").getString("PASSWORD CHANGED."));
            } else {
                JOptionPane.showInternalMessageDialog(databasePasswordPanel, "Something went wrong during password change.", "Password not changed.", JOptionPane.WARNING_MESSAGE);
            }
            changeDBPasswordButton.setEnabled(true);
        }
    }
}
