/*
 * RangeFilterPanel.java
 *
 * Created on 27 May 2008, 16:38
 */

package canreg.client.gui;

/**
 *
 * @author  ervikm
 */
public class RangeFilterPanel extends javax.swing.JPanel {
    
    /** Creates new form RangeFilterPanel */
    public RangeFilterPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rangePanel = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        limitsSplitPane = new javax.swing.JSplitPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        filterPanel = new javax.swing.JPanel();
        filterComboBox = new javax.swing.JComboBox();
        useFilterCheckBox = new javax.swing.JCheckBox();
        wizardButton = new javax.swing.JButton();
        recordsPanel = new javax.swing.JPanel();
        recordsShownField = new javax.swing.JTextField();
        recordsShownLabel = new javax.swing.JLabel();
        recordsTotalTextField = new javax.swing.JTextField();
        recordsTotalLabel = new javax.swing.JLabel();
        andLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        rangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Range"));
        rangePanel.setName("rangePanel"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Record Number", "ICD10", "Names" }));
        jComboBox2.setName("jComboBox2"); // NOI18N

        limitsSplitPane.setDividerLocation(100);
        limitsSplitPane.setResizeWeight(1.0);
        limitsSplitPane.setName("limitsSplitPane"); // NOI18N

        jTextField1.setName("jTextField1"); // NOI18N
        limitsSplitPane.setLeftComponent(jTextField1);

        jTextField2.setName("jTextField2"); // NOI18N
        limitsSplitPane.setRightComponent(jTextField2);

        javax.swing.GroupLayout rangePanelLayout = new javax.swing.GroupLayout(rangePanel);
        rangePanel.setLayout(rangePanelLayout);
        rangePanelLayout.setHorizontalGroup(
            rangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rangePanelLayout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitsSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        rangePanelLayout.setVerticalGroup(
            rangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(limitsSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
        filterPanel.setName("filterPanel"); // NOI18N

        filterComboBox.setEditable(true);
        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 2", "Item 3", "Item 4" }));
        filterComboBox.setEnabled(false);
        filterComboBox.setName("filterComboBox"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(RangeFilterPanel.class);
        useFilterCheckBox.setText(resourceMap.getString("useFilterCheckBox.text")); // NOI18N
        useFilterCheckBox.setName("useFilterCheckBox"); // NOI18N

        wizardButton.setText(resourceMap.getString("wizardButton.text")); // NOI18N
        wizardButton.setName("wizardButton"); // NOI18N

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filterComboBox, 0, 340, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                .addComponent(useFilterCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(wizardButton))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wizardButton)
                    .addComponent(useFilterCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        recordsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Records"));
        recordsPanel.setName("recordsPanel"); // NOI18N

        recordsShownField.setEditable(false);
        recordsShownField.setText(resourceMap.getString("recordsShownField.text")); // NOI18N
        recordsShownField.setName("recordsShownField"); // NOI18N

        recordsShownLabel.setText(resourceMap.getString("recordsShownLabel.text")); // NOI18N
        recordsShownLabel.setName("recordsShownLabel"); // NOI18N

        recordsTotalTextField.setEditable(false);
        recordsTotalTextField.setText(resourceMap.getString("recordsTotalTextField.text")); // NOI18N
        recordsTotalTextField.setName("recordsTotalTextField"); // NOI18N

        recordsTotalLabel.setText(resourceMap.getString("recordsTotalLabel.text")); // NOI18N
        recordsTotalLabel.setName("recordsTotalLabel"); // NOI18N

        javax.swing.GroupLayout recordsPanelLayout = new javax.swing.GroupLayout(recordsPanel);
        recordsPanel.setLayout(recordsPanelLayout);
        recordsPanelLayout.setHorizontalGroup(
            recordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordsShownField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordsShownLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recordsTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordsTotalLabel)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        recordsPanelLayout.setVerticalGroup(
            recordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordsPanelLayout.createSequentialGroup()
                .addGroup(recordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordsShownField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordsShownLabel)
                    .addComponent(recordsTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordsTotalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        andLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        andLabel.setText(resourceMap.getString("andLabel.text")); // NOI18N
        andLabel.setName("andLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(andLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recordsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andLabel;
    private javax.swing.JComboBox filterComboBox;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSplitPane limitsSplitPane;
    private javax.swing.JPanel rangePanel;
    private javax.swing.JPanel recordsPanel;
    private javax.swing.JTextField recordsShownField;
    private javax.swing.JLabel recordsShownLabel;
    private javax.swing.JLabel recordsTotalLabel;
    private javax.swing.JTextField recordsTotalTextField;
    private javax.swing.JCheckBox useFilterCheckBox;
    private javax.swing.JButton wizardButton;
    // End of variables declaration//GEN-END:variables
    
}
