#Everything can be manually updated except buildnum and builddate.
#Tue, 26 May 2026 12:29:16 +0200
program.BUILDNUM=1774
program.AUTHOR=Morten Johannes Ervik, CSU/IARC
program.BUILDDATE=20260526122916
program.DESCRIPTION=CanReg5 is a multi user, multi platform, open source tool to input, store, check and analyse cancer registry data.
program.COPYRIGHT=2008-2023
program.VERSION=5.00.44k
program.COMPANY=International Agency for Research on Cancer
program.PROGNAME=CanReg
