#Everything can be manually updated except buildnum and builddate.
#Mon, 25 May 2026 15:45:42 +0200
program.BUILDNUM=1758
program.AUTHOR=Morten Johannes Ervik, CSU/IARC
program.BUILDDATE=20260525154542
program.DESCRIPTION=CanReg5 is a multi user, multi platform, open source tool to input, store, check and analyse cancer registry data.
program.COPYRIGHT=2008-2023
program.VERSION=5.00.44k
program.COMPANY=International Agency for Research on Cancer
program.PROGNAME=CanReg
