/**
 * CanReg5 - a tool to input, store, check and analyse cancer registry data.
 * Copyright (C) 2008-2013  International Agency for Research on Cancer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Morten Johannes Ervik, CIN/IARC, ervikm@iarc.fr
 */

/*
 * DatabaseVariableEditorInternalFrame.java
 *
 * Created on 21-Jan-2010, 11:18:02
 */
package canreg.client.gui.management.systemeditor;

import canreg.common.DatabaseDictionaryListElement;
import canreg.common.DatabaseGroupsListElement;
import canreg.common.DatabaseVariablesListElement;
import canreg.common.Globals;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author ervikm
 */
public class DatabaseVariableEditorInternalFrame extends javax.swing.JInternalFrame {

    private ActionListener listener;
    public final static String UPDATED = "varaiable_updated";
    public final static String STANDARDVARIABLEMAPPINGCHANGED = "standard_variable_mapping_changed";
    private DatabaseVariablesListElement databaseVariablesListElement;
    private String originalTable;
    private String originalName;
    private int originalLength;
    private boolean originallyNumeric;

    /** Creates new form DatabaseVariableEditorInternalFrame */
    public DatabaseVariableEditorInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseVariableEditor = new canreg.client.gui.management.systemeditor.DatabaseVariableEditorPanel();

        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(DatabaseVariableEditorInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(DatabaseVariableEditorInternalFrame.class, this);
        okButton.setAction(actionMap.get("okAction")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancelAction")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        databaseVariableEditor.setName("databaseVariableEditor"); // NOI18N
        jScrollPane1.setViewportView(databaseVariableEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancelAction() {
        this.dispose();
    }

    @Action
    public void okAction() {
        try {
            databaseVariableEditor.refreshDatabaseVariablesListElement();
            if (databaseVariablesListElement.getDatabaseVariableName().length() == 0) {
                JOptionPane.showInternalMessageDialog(rootPane, "Short name can't be empty...");
            } else {
                if (originalLength != databaseVariablesListElement.getVariableLength()
                        || !originalName.equals(databaseVariablesListElement.getDatabaseVariableName())
                        || !originalTable.equals(databaseVariablesListElement.getDatabaseTableName())
                        || (originallyNumeric && !databaseVariablesListElement.getVariableType().equalsIgnoreCase(Globals.VARIABLE_TYPE_NUMBER_NAME))
                        || (!originallyNumeric && databaseVariablesListElement.getVariableType().equalsIgnoreCase(Globals.VARIABLE_TYPE_NUMBER_NAME))) {
                    listener.actionPerformed(new ActionEvent(this, 0, DatabaseElementPanel.STRUCTURE_CHANGE_ACTION));
                }
                listener.actionPerformed(new ActionEvent(this, 0, UPDATED));
                this.dispose();
            }
        } catch (DatabaseVariablesListException ex) {
            JOptionPane.showInternalMessageDialog(rootPane, ex.getDatabaseVariablesListElement().getDatabaseVariableName() + " : " + ex.getError());
            Logger.getLogger(DatabaseVariableEditorInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setDatabaseVariablesListElement(DatabaseVariablesListElement databaseVariablesListElement) {
        // this.setTitle(databaseVariablesListElement.getDatabaseVariableName());
        databaseVariableEditor.setDatabaseVariablesListElement(databaseVariablesListElement);
        this.databaseVariablesListElement = databaseVariablesListElement;
        originalTable = databaseVariablesListElement.getTable();
        originalName = databaseVariablesListElement.getDatabaseVariableName();
        originalLength = databaseVariablesListElement.getVariableLength();
        originallyNumeric = databaseVariablesListElement.getVariableType().equals(Globals.VARIABLE_TYPE_NUMBER_NAME);
    }

    public void setGroups(DatabaseGroupsListElement[] groups) {
        databaseVariableEditor.setGroups(groups);
    }

    public void setDictionaries(DatabaseDictionaryListElement[] dictionaries) {
        databaseVariableEditor.setDictionaries(dictionaries);
    }

    public void setActionListener(ActionListener listener) {
        this.listener = listener;
        databaseVariableEditor.setListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private canreg.client.gui.management.systemeditor.DatabaseVariableEditorPanel databaseVariableEditor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
