Args <- commandArgs(TRUE)
# garbage <- dev.off()
png(file=Args[1], bg="transparent")
par(bg = "gray")
pie(rep(1,24), col = rainbow(24), radius = 0.9)
dev.off()
cat(Args[1])
# cat("\n")
# cat(Args[2])
# cat("\n")
# cat(Args[3])