/**
 * CanReg5 - a tool to input, store, check and analyse cancer registry data.
 * Copyright (C) 2008-2011  International Agency for Research on Cancer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Morten Johannes Ervik, CIN/IARC, ervikm@iarc.fr
 */

/*
 * EditChecksInternalFrame.java
 *
 * Created on 29 February 2008, 13:51
 */

package canreg.client.gui.dataentry;

import canreg.client.gui.tools.globalpopup.MyPopUpMenu;
import org.jdesktop.application.Action;

/**
 *
 * @author  morten
 */
public class EditChecksInternalFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form EditChecksInternalFrame */
    public EditChecksInternalFrame() {
        initComponents();
        // TODO: Implement the name sex check
        nameSexPanel.setVisible(false);
        // TODO: Implement the local checks
        localChecksPanel.setVisible(false);
    }

    /**
     * 
     * @param text
     */
    public void setMandatoryVariablesTextAreaText(String text) {
        mandatoryVariablesTextArea.setText(text);
    }

    /**
     * 
     * @param text
     */
    public void setCrossChecksTextAreaText(String text) {
        crossChecksTextArea.setText(text);
    }
    
    /**
     * 
     * @param text
     */
    public void setNameSexChecksTextAreaText(String text) {
        nameSexTextArea.setText(text);
    }

    /**
     * 
     * @param text
     */
    public void setLocalChecksTextAreaText(String text) {
        localChecksTextArea.setText(text);
    }
    
    /**
     * 
     * @param text
     */
    public void setResultTextFieldText(String text) {
        resultTextField.setText(text);
    }
    
    /**
     * 
     * @param text
     */
    public void setICD10TextFieldText(String text) {
        ICD10TextField.setText(text);
    }
    
    /**
     * 
     * @param text
     */
    public void setICCCTextFieldText(String text) {
        ICCCTextField.setText(text);
    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mandatoryVariablesPanel = new javax.swing.JPanel();
        mandatoryVariablesScrollPane = new javax.swing.JScrollPane();
        mandatoryVariablesTextArea = new javax.swing.JTextArea();
        crossChecksPanel = new javax.swing.JPanel();
        crossChecksScrollPane = new javax.swing.JScrollPane();
        crossChecksTextArea = new javax.swing.JTextArea();
        nameSexPanel = new javax.swing.JPanel();
        nameSexScrollPane = new javax.swing.JScrollPane();
        nameSexTextArea = new javax.swing.JTextArea();
        localChecksPanel = new javax.swing.JPanel();
        localChecksScrollPane = new javax.swing.JScrollPane();
        localChecksTextArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        ICD10Label = new javax.swing.JLabel();
        ICD10TextField = new javax.swing.JTextField();
        ICCCLabel = new javax.swing.JLabel();
        ICCCTextField = new javax.swing.JTextField();
        resultPanel = new javax.swing.JPanel();
        resultTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(EditChecksInternalFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setDoubleBuffered(true);
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        mandatoryVariablesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("mandatoryVariablesPanel.border.title"))); // NOI18N
        mandatoryVariablesPanel.setName("mandatoryVariablesPanel"); // NOI18N

        mandatoryVariablesScrollPane.setName("mandatoryVariablesScrollPane"); // NOI18N

        mandatoryVariablesTextArea.setColumns(20);
        mandatoryVariablesTextArea.setEditable(false);
        mandatoryVariablesTextArea.setRows(5);
        mandatoryVariablesTextArea.setText(resourceMap.getString("mandatoryVariablesTextArea.text")); // NOI18N
        mandatoryVariablesTextArea.setName("mandatoryVariablesTextArea"); // NOI18N
        mandatoryVariablesTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mandatoryVariablesTextAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mandatoryVariablesTextAreaMouseReleased(evt);
            }
        });
        mandatoryVariablesScrollPane.setViewportView(mandatoryVariablesTextArea);

        javax.swing.GroupLayout mandatoryVariablesPanelLayout = new javax.swing.GroupLayout(mandatoryVariablesPanel);
        mandatoryVariablesPanel.setLayout(mandatoryVariablesPanelLayout);
        mandatoryVariablesPanelLayout.setHorizontalGroup(
            mandatoryVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mandatoryVariablesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        mandatoryVariablesPanelLayout.setVerticalGroup(
            mandatoryVariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mandatoryVariablesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        crossChecksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("crossChecksPanel.border.title"))); // NOI18N
        crossChecksPanel.setName("crossChecksPanel"); // NOI18N

        crossChecksScrollPane.setName("crossChecksScrollPane"); // NOI18N

        crossChecksTextArea.setColumns(20);
        crossChecksTextArea.setEditable(false);
        crossChecksTextArea.setRows(5);
        crossChecksTextArea.setText(resourceMap.getString("crossChecksTextArea.text")); // NOI18N
        crossChecksTextArea.setName("crossChecksTextArea"); // NOI18N
        crossChecksTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crossChecksTextAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crossChecksTextAreaMouseReleased(evt);
            }
        });
        crossChecksScrollPane.setViewportView(crossChecksTextArea);

        javax.swing.GroupLayout crossChecksPanelLayout = new javax.swing.GroupLayout(crossChecksPanel);
        crossChecksPanel.setLayout(crossChecksPanelLayout);
        crossChecksPanelLayout.setHorizontalGroup(
            crossChecksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crossChecksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        crossChecksPanelLayout.setVerticalGroup(
            crossChecksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crossChecksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        nameSexPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("nameSexPanel.border.title"))); // NOI18N
        nameSexPanel.setName("nameSexPanel"); // NOI18N

        nameSexScrollPane.setName("nameSexScrollPane"); // NOI18N

        nameSexTextArea.setColumns(20);
        nameSexTextArea.setEditable(false);
        nameSexTextArea.setRows(5);
        nameSexTextArea.setText(resourceMap.getString("nameSexTextArea.text")); // NOI18N
        nameSexTextArea.setName("nameSexTextArea"); // NOI18N
        nameSexTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameSexTextAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nameSexTextAreaMouseReleased(evt);
            }
        });
        nameSexScrollPane.setViewportView(nameSexTextArea);

        javax.swing.GroupLayout nameSexPanelLayout = new javax.swing.GroupLayout(nameSexPanel);
        nameSexPanel.setLayout(nameSexPanelLayout);
        nameSexPanelLayout.setHorizontalGroup(
            nameSexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameSexScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        nameSexPanelLayout.setVerticalGroup(
            nameSexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameSexScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        localChecksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("localChecksPanel.border.title"))); // NOI18N
        localChecksPanel.setName("localChecksPanel"); // NOI18N

        localChecksScrollPane.setName("localChecksScrollPane"); // NOI18N

        localChecksTextArea.setColumns(20);
        localChecksTextArea.setEditable(false);
        localChecksTextArea.setRows(5);
        localChecksTextArea.setText(resourceMap.getString("localChecksTextArea.text")); // NOI18N
        localChecksTextArea.setEnabled(false);
        localChecksTextArea.setName("localChecksTextArea"); // NOI18N
        localChecksTextArea.setOpaque(false);
        localChecksTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                localChecksTextAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                localChecksTextAreaMouseReleased(evt);
            }
        });
        localChecksScrollPane.setViewportView(localChecksTextArea);

        javax.swing.GroupLayout localChecksPanelLayout = new javax.swing.GroupLayout(localChecksPanel);
        localChecksPanel.setLayout(localChecksPanelLayout);
        localChecksPanelLayout.setHorizontalGroup(
            localChecksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(localChecksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        localChecksPanelLayout.setVerticalGroup(
            localChecksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(localChecksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        ICD10Label.setText(resourceMap.getString("ICD10Label.text")); // NOI18N
        ICD10Label.setName("ICD10Label"); // NOI18N

        ICD10TextField.setEditable(false);
        ICD10TextField.setText(resourceMap.getString("ICD10TextField.text")); // NOI18N
        ICD10TextField.setName("ICD10TextField"); // NOI18N
        ICD10TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ICD10TextFieldMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ICD10TextFieldMouseReleased(evt);
            }
        });

        ICCCLabel.setText(resourceMap.getString("ICCCLabel.text")); // NOI18N
        ICCCLabel.setName("ICCCLabel"); // NOI18N

        ICCCTextField.setEditable(false);
        ICCCTextField.setText(resourceMap.getString("ICCCTextField.text")); // NOI18N
        ICCCTextField.setName("ICCCTextField"); // NOI18N
        ICCCTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ICCCTextFieldMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ICCCTextFieldMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ICD10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICD10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ICCCLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(ICCCTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICD10Label)
                    .addComponent(ICCCLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICD10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICCCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        resultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("resultPanel.border.title"))); // NOI18N
        resultPanel.setName("resultPanel"); // NOI18N

        resultTextField.setEditable(false);
        resultTextField.setText(resourceMap.getString("resultTextField.text")); // NOI18N
        resultTextField.setName("resultTextField"); // NOI18N
        resultTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultTextFieldMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resultTextFieldMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(EditChecksInternalFrame.class, this);
        okButton.setAction(actionMap.get("okAction")); // NOI18N
        okButton.setIcon(resourceMap.getIcon("okButton.icon")); // NOI18N
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crossChecksPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameSexPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mandatoryVariablesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addComponent(localChecksPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mandatoryVariablesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSexPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crossChecksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localChecksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mandatoryVariablesTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mandatoryVariablesTextAreaMousePressed
         MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(mandatoryVariablesTextArea, evt);
    }//GEN-LAST:event_mandatoryVariablesTextAreaMousePressed

    private void mandatoryVariablesTextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mandatoryVariablesTextAreaMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(mandatoryVariablesTextArea, evt);
    }//GEN-LAST:event_mandatoryVariablesTextAreaMouseReleased

    private void nameSexTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSexTextAreaMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(nameSexTextArea, evt);
    }//GEN-LAST:event_nameSexTextAreaMousePressed

    private void nameSexTextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSexTextAreaMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(nameSexTextArea, evt);
    }//GEN-LAST:event_nameSexTextAreaMouseReleased

    private void crossChecksTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossChecksTextAreaMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(crossChecksTextArea, evt);
    }//GEN-LAST:event_crossChecksTextAreaMousePressed

    private void crossChecksTextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossChecksTextAreaMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(crossChecksTextArea, evt);
    }//GEN-LAST:event_crossChecksTextAreaMouseReleased

    private void localChecksTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localChecksTextAreaMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(localChecksTextArea, evt);
    }//GEN-LAST:event_localChecksTextAreaMousePressed

    private void localChecksTextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localChecksTextAreaMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(localChecksTextArea, evt);
    }//GEN-LAST:event_localChecksTextAreaMouseReleased

    private void ICD10TextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ICD10TextFieldMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(ICD10TextField, evt);
    }//GEN-LAST:event_ICD10TextFieldMousePressed

    private void ICD10TextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ICD10TextFieldMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(ICD10TextField, evt);
    }//GEN-LAST:event_ICD10TextFieldMouseReleased

    private void ICCCTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ICCCTextFieldMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(ICCCTextField, evt);
    }//GEN-LAST:event_ICCCTextFieldMousePressed

    private void ICCCTextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ICCCTextFieldMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(ICCCTextField, evt);
    }//GEN-LAST:event_ICCCTextFieldMouseReleased

    private void resultTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTextFieldMousePressed
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(resultTextField, evt);
    }//GEN-LAST:event_resultTextFieldMousePressed

    private void resultTextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTextFieldMouseReleased
        MyPopUpMenu.potentiallyShowPopUpMenuTextComponent(resultTextField, evt);
    }//GEN-LAST:event_resultTextFieldMouseReleased

    /**
     * 
     */
    @Action
    public void okAction() {
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICCCLabel;
    private javax.swing.JTextField ICCCTextField;
    private javax.swing.JLabel ICD10Label;
    private javax.swing.JTextField ICD10TextField;
    private javax.swing.JPanel crossChecksPanel;
    private javax.swing.JScrollPane crossChecksScrollPane;
    private javax.swing.JTextArea crossChecksTextArea;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel localChecksPanel;
    private javax.swing.JScrollPane localChecksScrollPane;
    private javax.swing.JTextArea localChecksTextArea;
    private javax.swing.JPanel mandatoryVariablesPanel;
    private javax.swing.JScrollPane mandatoryVariablesScrollPane;
    private javax.swing.JTextArea mandatoryVariablesTextArea;
    private javax.swing.JPanel nameSexPanel;
    private javax.swing.JScrollPane nameSexScrollPane;
    private javax.swing.JTextArea nameSexTextArea;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextField resultTextField;
    // End of variables declaration//GEN-END:variables
    
}
