/*
 * ImportView.java
 *
 * Created on 22 February 2008, 09:30
 */
package canreg.client.gui.dataentry;

import canreg.client.gui.components.VariableMappingPanel;
import canreg.client.LocalSettings;
import canreg.client.CanRegClientApp;
import canreg.common.DatabaseVariablesListElement;
import canreg.client.dataentry.Import;
import canreg.client.dataentry.ImportOptions;
import canreg.client.dataentry.Relation;
import canreg.client.gui.components.PreviewFilePanel;
import canreg.client.gui.components.VariableMappingAlternativePanel;
import canreg.common.GlobalToolBox;
import canreg.common.Globals;
import canreg.server.database.RecordLockedException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.w3c.dom.Document;

/**
 *
 * @author  morten
 * 
 * This module 
 * 
 * TODO: Accept various date formats?
 * Implement the various options
 * 
 * 
 */
public class ImportFilesView extends javax.swing.JInternalFrame implements ActionListener {

    private boolean needToRebuildVariableMap = true;
    private File patientInFile;
    private File tumourInFile;
    private File sourceInFile;
    private Document doc;
    private DatabaseVariablesListElement[] patientVariablesInDB;
    private DatabaseVariablesListElement[] tumourVariablesInDB;
    private DatabaseVariablesListElement[] sourceVariablesInDB;
    private String path;
    private LocalSettings localSettings;
    private GlobalToolBox globalToolBox;
    private Task importTask;

    /** Creates new form ImportView */
    public ImportFilesView() {
        initComponents();
        // previewPanel.setVisible(false);

        globalToolBox = CanRegClientApp.getApplication().getGlobalToolBox();

        changeTab(0);

        // Add a listener for changing the active tab
        ChangeListener tabbedPaneChangeListener = new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                initializeVariableMappingTab();
                changeTab(tabbedPane.getSelectedIndex());
            }
        };

        patientPreviewFilePanel.init(this);
        tumourPreviewFilePanel.init(this);
        sourcePreviewFilePanel.init(this);

        // And add the listener to the tabbedPane
        tabbedPane.addChangeListener(tabbedPaneChangeListener);

        localSettings = CanRegClientApp.getApplication().getLocalSettings();
        path = localSettings.getProperty("import_path");

        patientPreviewFilePanel.setPath(path);
        tumourPreviewFilePanel.setPath(path);
        sourcePreviewFilePanel.setPath(path);

        // Group the radiobuttons
        ButtonGroup discrepanciesButtonGroup = new ButtonGroup();
        // Add to the button group
        discrepanciesButtonGroup.add(rejectRadioButton);
        discrepanciesButtonGroup.add(updateRadioButton);
        discrepanciesButtonGroup.add(overwriteRadioButton);

        // Get the system description
        doc = CanRegClientApp.getApplication().getDatabseDescription();
        // variablesInDB = canreg.common.Tools.getVariableListElements(doc, Globals.NAMESPACE);
        patientVariablesInDB = canreg.common.Tools.getVariableListElements(doc, Globals.NAMESPACE, Globals.PATIENT_TABLE_NAME);
        tumourVariablesInDB = canreg.common.Tools.getVariableListElements(doc, Globals.NAMESPACE, Globals.TUMOUR_TABLE_NAME);
        sourceVariablesInDB = canreg.common.Tools.getVariableListElements(doc, Globals.NAMESPACE, Globals.SOURCE_TABLE_NAME);
    }

    private void changeTab(int tabNumber) {
        tabbedPane.setSelectedIndex(tabNumber);
        nextButton.setEnabled(tabNumber < tabbedPane.getTabCount() - 1);
        backButton.setEnabled(tabNumber > 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        chooseFilesTabbedPane = new javax.swing.JTabbedPane();
        patientPreviewFilePanel = new canreg.client.gui.components.PreviewFilePanel();
        tumourPreviewFilePanel = new canreg.client.gui.components.PreviewFilePanel();
        sourcePreviewFilePanel = new canreg.client.gui.components.PreviewFilePanel();
        associateVariavlesTabbedPane = new javax.swing.JTabbedPane();
        patientVariablesAssociationPanel = new canreg.client.gui.components.VariablesAssociationPanel();
        tumourVariablesAssociationPanel = new canreg.client.gui.components.VariablesAssociationPanel();
        sourceVariablesAssociationPanel = new canreg.client.gui.components.VariablesAssociationPanel();
        importFilePanel = new javax.swing.JPanel();
        importButton = new javax.swing.JButton();
        discrepanciesPanel = new javax.swing.JPanel();
        rejectRadioButton = new javax.swing.JRadioButton();
        updateRadioButton = new javax.swing.JRadioButton();
        overwriteRadioButton = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        doChecksCheckBox = new javax.swing.JCheckBox();
        personSearchCheckBox = new javax.swing.JCheckBox();
        queryNewNameCheckBox = new javax.swing.JCheckBox();
        previousCanRegDataCheckBox = new javax.swing.JCheckBox();
        maxLinesPanel = new javax.swing.JPanel();
        maxLinesTextField = new javax.swing.JTextField();
        testOnlyCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getResourceMap(ImportFilesView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        tabbedPane.setName("tabbedPane"); // NOI18N

        chooseFilesTabbedPane.setName("chooseFilesTabbedPane"); // NOI18N

        patientPreviewFilePanel.setName("patientPreviewFilePanel"); // NOI18N
        chooseFilesTabbedPane.addTab(resourceMap.getString("patientPreviewFilePanel.TabConstraints.tabTitle"), patientPreviewFilePanel); // NOI18N

        tumourPreviewFilePanel.setName("tumourPreviewFilePanel"); // NOI18N
        chooseFilesTabbedPane.addTab(resourceMap.getString("tumourPreviewFilePanel.TabConstraints.tabTitle"), tumourPreviewFilePanel); // NOI18N

        sourcePreviewFilePanel.setName("sourcePreviewFilePanel"); // NOI18N
        chooseFilesTabbedPane.addTab(resourceMap.getString("sourcePreviewFilePanel.TabConstraints.tabTitle"), sourcePreviewFilePanel); // NOI18N

        tabbedPane.addTab(resourceMap.getString("chooseFilesTabbedPane.TabConstraints.tabTitle"), chooseFilesTabbedPane); // NOI18N

        associateVariavlesTabbedPane.setName("associateVariavlesTabbedPane"); // NOI18N

        patientVariablesAssociationPanel.setName("patientVariablesAssociationPanel"); // NOI18N
        associateVariavlesTabbedPane.addTab(resourceMap.getString("patientVariablesAssociationPanel.TabConstraints.tabTitle"), patientVariablesAssociationPanel); // NOI18N

        tumourVariablesAssociationPanel.setName("tumourVariablesAssociationPanel"); // NOI18N
        associateVariavlesTabbedPane.addTab(resourceMap.getString("tumourVariablesAssociationPanel.TabConstraints.tabTitle"), tumourVariablesAssociationPanel); // NOI18N

        sourceVariablesAssociationPanel.setName("sourceVariablesAssociationPanel"); // NOI18N
        associateVariavlesTabbedPane.addTab(resourceMap.getString("sourceVariablesAssociationPanel.TabConstraints.tabTitle"), sourceVariablesAssociationPanel); // NOI18N

        tabbedPane.addTab(resourceMap.getString("associateVariavlesTabbedPane.TabConstraints.tabTitle"), associateVariavlesTabbedPane); // NOI18N

        importFilePanel.setName("importFilePanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class).getContext().getActionMap(ImportFilesView.class, this);
        importButton.setAction(actionMap.get("importAction")); // NOI18N
        importButton.setName("importButton"); // NOI18N

        discrepanciesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Discrepancies"));
        discrepanciesPanel.setToolTipText(resourceMap.getString("discrepanciesPanel.toolTipText")); // NOI18N
        discrepanciesPanel.setEnabled(false);
        discrepanciesPanel.setName("discrepanciesPanel"); // NOI18N

        rejectRadioButton.setText(resourceMap.getString("rejectRadioButton.text")); // NOI18N
        rejectRadioButton.setEnabled(false);
        rejectRadioButton.setName("rejectRadioButton"); // NOI18N

        updateRadioButton.setSelected(true);
        updateRadioButton.setText(resourceMap.getString("updateRadioButton.text")); // NOI18N
        updateRadioButton.setEnabled(false);
        updateRadioButton.setName("updateRadioButton"); // NOI18N

        overwriteRadioButton.setText(resourceMap.getString("overwriteRadioButton.text")); // NOI18N
        overwriteRadioButton.setEnabled(false);
        overwriteRadioButton.setName("overwriteRadioButton"); // NOI18N

        javax.swing.GroupLayout discrepanciesPanelLayout = new javax.swing.GroupLayout(discrepanciesPanel);
        discrepanciesPanel.setLayout(discrepanciesPanelLayout);
        discrepanciesPanelLayout.setHorizontalGroup(
            discrepanciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discrepanciesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(discrepanciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rejectRadioButton)
                    .addComponent(updateRadioButton)
                    .addComponent(overwriteRadioButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        discrepanciesPanelLayout.setVerticalGroup(
            discrepanciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discrepanciesPanelLayout.createSequentialGroup()
                .addComponent(rejectRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overwriteRadioButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("CanReg data"));
        jPanel7.setName("jPanel7"); // NOI18N

        doChecksCheckBox.setText(resourceMap.getString("doChecksCheckBox.text")); // NOI18N
        doChecksCheckBox.setToolTipText(resourceMap.getString("doChecksCheckBox.toolTipText")); // NOI18N
        doChecksCheckBox.setEnabled(false);
        doChecksCheckBox.setName("doChecksCheckBox"); // NOI18N

        personSearchCheckBox.setSelected(true);
        personSearchCheckBox.setText(resourceMap.getString("personSearchCheckBox.text")); // NOI18N
        personSearchCheckBox.setToolTipText(resourceMap.getString("personSearchCheckBox.toolTipText")); // NOI18N
        personSearchCheckBox.setEnabled(false);
        personSearchCheckBox.setName("personSearchCheckBox"); // NOI18N

        queryNewNameCheckBox.setSelected(true);
        queryNewNameCheckBox.setText(resourceMap.getString("queryNewNameCheckBox.text")); // NOI18N
        queryNewNameCheckBox.setToolTipText(resourceMap.getString("queryNewNameCheckBox.toolTipText")); // NOI18N
        queryNewNameCheckBox.setEnabled(false);
        queryNewNameCheckBox.setName("queryNewNameCheckBox"); // NOI18N

        previousCanRegDataCheckBox.setSelected(true);
        previousCanRegDataCheckBox.setText(resourceMap.getString("previousCanRegDataCheckBox.text")); // NOI18N
        previousCanRegDataCheckBox.setToolTipText(resourceMap.getString("previousCanRegDataCheckBox.toolTipText")); // NOI18N
        previousCanRegDataCheckBox.setName("previousCanRegDataCheckBox"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doChecksCheckBox)
                    .addComponent(personSearchCheckBox)
                    .addComponent(queryNewNameCheckBox)
                    .addComponent(previousCanRegDataCheckBox))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(doChecksCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personSearchCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryNewNameCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousCanRegDataCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        maxLinesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Max Lines"));
        maxLinesPanel.setName("maxLinesPanel"); // NOI18N

        maxLinesTextField.setToolTipText(resourceMap.getString("maxLinesTextField.toolTipText")); // NOI18N
        maxLinesTextField.setName("maxLinesTextField"); // NOI18N

        testOnlyCheckBox.setText(resourceMap.getString("testOnlyCheckBox.text")); // NOI18N
        testOnlyCheckBox.setToolTipText(resourceMap.getString("testOnlyCheckBox.toolTipText")); // NOI18N
        testOnlyCheckBox.setName("testOnlyCheckBox"); // NOI18N

        javax.swing.GroupLayout maxLinesPanelLayout = new javax.swing.GroupLayout(maxLinesPanel);
        maxLinesPanel.setLayout(maxLinesPanelLayout);
        maxLinesPanelLayout.setHorizontalGroup(
            maxLinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maxLinesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxLinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testOnlyCheckBox)
                    .addComponent(maxLinesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addContainerGap())
        );
        maxLinesPanelLayout.setVerticalGroup(
            maxLinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxLinesPanelLayout.createSequentialGroup()
                .addComponent(maxLinesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testOnlyCheckBox)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout importFilePanelLayout = new javax.swing.GroupLayout(importFilePanel);
        importFilePanel.setLayout(importFilePanelLayout);
        importFilePanelLayout.setHorizontalGroup(
            importFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importFilePanelLayout.createSequentialGroup()
                        .addComponent(discrepanciesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxLinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        importFilePanelLayout.setVerticalGroup(
            importFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(discrepanciesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxLinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importButton)
                .addGap(318, 318, 318))
        );

        tabbedPane.addTab("Import File", importFilePanel);

        nextButton.setAction(actionMap.get("jumpToNextTabAction")); // NOI18N
        nextButton.setName("nextButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancelAction")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        backButton.setAction(actionMap.get("jumpToPreviousTabAction")); // NOI18N
        backButton.setName("backButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton))
                    .addComponent(tabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(cancelButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     */
    @Action
    public void jumpToNextTabAction() {
        initializeVariableMappingTab();
        int tabNumber = tabbedPane.getSelectedIndex();
        if (tabNumber < tabbedPane.getTabCount()) {
            tabbedPane.setSelectedIndex(++tabNumber);
            changeTab(tabNumber);
        }
    }

    /**
     * 
     */
    @Action
    public void jumpToPreviousTabAction() {
        initializeVariableMappingTab();
        int tabNumber = tabbedPane.getSelectedIndex();
        if (tabNumber >= 1) {
            tabbedPane.setSelectedIndex(--tabNumber);
            changeTab(tabNumber);
        }
    }

    /**
     * 
     */
    @Action
    public void cancelAction() {
        if (importTask != null) {
            if (JOptionPane.showInternalConfirmDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Do you really want to cancel the import process?", "Please confirm.", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                importTask.cancel(true);
                JOptionPane.showInternalMessageDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Import of file interupted.", "Warning.", JOptionPane.WARNING_MESSAGE);
                importTask = null;
                this.dispose();
            }
        } else {
            this.dispose();
        }
    }

    /**
     * 
     * @return
     */
    @Action()
    public Task importAction() {
        // TODO: Add a handler for errors in the file structure...
        localSettings.setProperty("import_path", path);
        localSettings.writeSettings();
        progressBar.setStringPainted(true);
        importButton.setEnabled(false);
        // this.dispose();
        importTask = new ImportActionTask(org.jdesktop.application.Application.getInstance(canreg.client.CanRegClientApp.class));
        importTask.addPropertyChangeListener(new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent evt) {
                if ("progress".equals(evt.getPropertyName())) {
                    progressBar.setValue((Integer) evt.getNewValue());
                    progressBar.setString(evt.getNewValue().toString() + "%");
                } else if ("finished".equals(evt.getPropertyName())) {
                    dispose();
                }
            }
        });
        return importTask;
    }

    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals(PreviewFilePanel.FILE_CHANGED_ACTION)) {
            needToRebuildVariableMap = true;
        }
    }

    private class ImportActionTask extends org.jdesktop.application.Task<Object, Void> {

        ImportActionTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to ImportActionTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            boolean success = false;
            try {
                // Calls the client app import action with the file parameters provided,
                success = CanRegClientApp.getApplication().importFiles(this, doc, buildMap(), new File[]{patientInFile, tumourInFile, sourceInFile}, buildImportOptions());
            } catch (SecurityException ex) {
                Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RecordLockedException ex) {
                Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
                success = false;
            }
            return success;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
            if (!(Boolean) result) {
                JOptionPane.showInternalMessageDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Something wrong with the file " + patientInFile.getAbsolutePath() + ".", "File NOT successfully imported", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showInternalMessageDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Successfully imported file " + patientInFile.getAbsolutePath() + ".", "File successfully imported", JOptionPane.INFORMATION_MESSAGE);
            }
            importTask = null;
        }
    }

    private void initializeVariableMappingTab() {
        BufferedReader br = null;
        try {
            // patient mapping
            patientInFile = patientPreviewFilePanel.getInFile();
            if (needToRebuildVariableMap && patientInFile != null) {
                br = new BufferedReader(new FileReader(patientInFile));
                String line = br.readLine();
                String[] lineElements = canreg.common.Tools.breakDownLine(patientPreviewFilePanel.getSeparator(), line);
                List<Relation> map = Import.constructRelations(doc, lineElements);
                patientVariablesAssociationPanel.initializeVariableMappingPanel(map, patientVariablesInDB, lineElements);
            }
            // tumour mapping
            tumourInFile = tumourPreviewFilePanel.getInFile();
            if (needToRebuildVariableMap && tumourInFile != null) {
                br = new BufferedReader(new FileReader(tumourInFile));
                String line = br.readLine();
                String[] lineElements = canreg.common.Tools.breakDownLine(tumourPreviewFilePanel.getSeparator(), line);
                List<Relation> map = Import.constructRelations(doc, lineElements);
                tumourVariablesAssociationPanel.initializeVariableMappingPanel(map, tumourVariablesInDB, lineElements);
            }
            // source mapping
            sourceInFile = sourcePreviewFilePanel.getInFile();
            if (needToRebuildVariableMap && sourceInFile != null) {
                br = new BufferedReader(new FileReader(sourceInFile));
                String line = br.readLine();
                String[] lineElements = canreg.common.Tools.breakDownLine(sourcePreviewFilePanel.getSeparator(), line);
                List<Relation> map = Import.constructRelations(doc, lineElements);
                sourceVariablesAssociationPanel.initializeVariableMappingPanel(map, sourceVariablesInDB, lineElements);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Could not open file: \'" + patientInFile.getPath() + "\'.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            needToRebuildVariableMap = false;
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(ImportFilesView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private List<Relation> buildMap() {
        List<Relation> map = new LinkedList();
        for (VariableMappingAlternativePanel vmp : patientVariablesAssociationPanel.getPanelList()) {
            Relation rel = new Relation();
            int fileColumnNumber = vmp.getSelectedFileColumnNumber();
            if (fileColumnNumber >= 0) {
                DatabaseVariablesListElement dbVLE = vmp.getDatabaseVariablesListElement();
                rel.setDatabaseTableName(dbVLE.getDatabaseTableName());
                rel.setDatabaseTableVariableID(vmp.getDBVariableIndex());
                rel.setDatabaseVariableName(dbVLE.getDatabaseVariableName());
                rel.setFileColumnNumber(fileColumnNumber);
                rel.setFileVariableName(vmp.getSelectedFileElement());
                rel.setVariableType(dbVLE.getVariableType());
                map.add(rel);
            }
        }
        for (VariableMappingAlternativePanel vmp : tumourVariablesAssociationPanel.getPanelList()) {
            Relation rel = new Relation();
            int fileColumnNumber = vmp.getSelectedFileColumnNumber();
            if (fileColumnNumber >= 0) {
                DatabaseVariablesListElement dbVLE = vmp.getDatabaseVariablesListElement();
                rel.setDatabaseTableName(dbVLE.getDatabaseTableName());
                rel.setDatabaseTableVariableID(vmp.getDBVariableIndex());
                rel.setDatabaseVariableName(dbVLE.getDatabaseVariableName());
                rel.setFileColumnNumber(fileColumnNumber);
                rel.setFileVariableName(vmp.getSelectedFileElement());
                rel.setVariableType(dbVLE.getVariableType());
                map.add(rel);
            }
        }
        for (VariableMappingAlternativePanel vmp : sourceVariablesAssociationPanel.getPanelList()) {
            Relation rel = new Relation();
            int fileColumnNumber = vmp.getSelectedFileColumnNumber();
            if (fileColumnNumber >= 0) {
                DatabaseVariablesListElement dbVLE = vmp.getDatabaseVariablesListElement();
                rel.setDatabaseTableName(dbVLE.getDatabaseTableName());
                rel.setDatabaseTableVariableID(vmp.getDBVariableIndex());
                rel.setDatabaseVariableName(dbVLE.getDatabaseVariableName());
                rel.setFileColumnNumber(fileColumnNumber);
                rel.setFileVariableName(vmp.getSelectedFileElement());
                rel.setVariableType(dbVLE.getVariableType());
                map.add(rel);
            }
        }
        return map;
    }

    private ImportOptions buildImportOptions() {
        ImportOptions io = new ImportOptions();

        // Discrepencies
        if (updateRadioButton.isSelected()) {
            io.setDiscrepancies(ImportOptions.UPDATE);
        } else if (rejectRadioButton.isSelected()) {
            io.setDiscrepancies(ImportOptions.REJECT);
        } else if (overwriteRadioButton.isSelected()) {
            io.setDiscrepancies(ImportOptions.OVERWRITE);
        }
        // Max Lines
        if (maxLinesTextField.getText().trim().length() > 0) {
            io.setMaxLines(Integer.parseInt(maxLinesTextField.getText().trim()));
        } else {
            io.setMaxLines(-1);
        }
        io.setTestOnly(testOnlyCheckBox.isSelected());

        // separators
        io.setSeparators(new char[]{
                    patientPreviewFilePanel.getSeparator(),
                    tumourPreviewFilePanel.getSeparator(),
                    sourcePreviewFilePanel.getSeparator()
                });

        // CanReg data
        io.setDoChecks(doChecksCheckBox.isSelected());
        io.setDoPersonSearch(personSearchCheckBox.isSelected());
        io.setQueryNewNames(queryNewNameCheckBox.isSelected());
        io.setDataFromPreviousCanReg(previousCanRegDataCheckBox.isSelected());

        // Set standard variable names
        io.setMultiplePrimaryVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.MultPrimCode.toString()).getDatabaseVariableName());
        io.setPatientIDTumourTableVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.PatientIDTumourTable.toString()).getDatabaseVariableName());
        io.setPatientIDVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.PatientID.toString()).getDatabaseVariableName());
        io.setTumourUpdateDateVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.TumourUpdateDate.toString()).getDatabaseVariableName());
        io.setPatientUpdateDateVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.PatientUpdateDate.toString()).getDatabaseVariableName());
        io.setTumourIDVariablename(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.TumourID.toString()).getDatabaseVariableName());
        io.setPatientRecordIDVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.PatientRecordID.toString()).getDatabaseVariableName());
        io.setPatientRecordIDTumourTableVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.PatientRecordIDTumourTable.toString()).getDatabaseVariableName());
        io.setTumourIDSourceTableVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.TumourIDSourceTable.toString()).getDatabaseVariableName());
        io.setObsoletePatientFlagVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.ObsoleteFlagPatientTable.toString()).getDatabaseVariableName());
        io.setObsoleteTumourFlagVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.ObsoleteFlagTumourTable.toString()).getDatabaseVariableName());
        io.setTumourSequenceVariableName(globalToolBox.translateStandardVariableNameToDatabaseListElement(Globals.StandardVariableNames.MultPrimSeq.toString()).getDatabaseVariableName());

        // Set the charactersets
        io.setFilesCharsets(getCharsets());

        return io;
    }

    private Charset[] getCharsets() {
        // get one from each table
        return new Charset[]{
                    patientPreviewFilePanel.getCharacterSet(),
                    tumourPreviewFilePanel.getCharacterSet(),
                    sourcePreviewFilePanel.getCharacterSet()
                };
    }

    /**
     * 
     */
    @Action
    public void comboBoxChanged() {
        needToRebuildVariableMap = true;
    }

    /**
     * 
     */
    @Action
    public void autodetectSeparatingCharacterAction() {
        JOptionPane.showInternalMessageDialog(CanRegClientApp.getApplication().getMainFrame().getContentPane(), "Not yet implemented.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane associateVariavlesTabbedPane;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTabbedPane chooseFilesTabbedPane;
    private javax.swing.JPanel discrepanciesPanel;
    private javax.swing.JCheckBox doChecksCheckBox;
    private javax.swing.JButton importButton;
    private javax.swing.JPanel importFilePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel maxLinesPanel;
    private javax.swing.JTextField maxLinesTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton overwriteRadioButton;
    private canreg.client.gui.components.PreviewFilePanel patientPreviewFilePanel;
    private canreg.client.gui.components.VariablesAssociationPanel patientVariablesAssociationPanel;
    private javax.swing.JCheckBox personSearchCheckBox;
    private javax.swing.JCheckBox previousCanRegDataCheckBox;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JCheckBox queryNewNameCheckBox;
    private javax.swing.JRadioButton rejectRadioButton;
    private canreg.client.gui.components.PreviewFilePanel sourcePreviewFilePanel;
    private canreg.client.gui.components.VariablesAssociationPanel sourceVariablesAssociationPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBox testOnlyCheckBox;
    private canreg.client.gui.components.PreviewFilePanel tumourPreviewFilePanel;
    private canreg.client.gui.components.VariablesAssociationPanel tumourVariablesAssociationPanel;
    private javax.swing.JRadioButton updateRadioButton;
    // End of variables declaration//GEN-END:variables
}
